/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package switchsetup.view;

import static switchsetup.view.Setups.*;

/**
 *
 * @author samuel.montoya
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setupMenuButton(irfButton, "/resources/netButtonMenu.png");
        setupMenuButton(linkButton, "/resources/netButtonMenu.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        irfButton = new javax.swing.JButton();
        linkButton = new javax.swing.JButton();

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/netLogo.png"))); // NOI18N
        logoLabel.setToolTipText("");

        irfButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/netButtonMenu.png"))); // NOI18N
        irfButton.setText("IRF BUTTON");
        irfButton.setBounds(new java.awt.Rectangle(300, 200, 97, 29));
        irfButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irfButton.setPreferredSize(new java.awt.Dimension(400, 180));

        linkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/netButtonMenu.png"))); // NOI18N
        linkButton.setLabel("LINK AGGREGATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(logoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(irfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(linkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoLabel)
                .addGap(18, 18, 18)
                .addComponent(irfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linkButton)
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton irfButton;
    private javax.swing.JButton linkButton;
    private javax.swing.JLabel logoLabel;
    // End of variables declaration//GEN-END:variables
}
